import {
  Activity,
  AlertTriangle,
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  Bell,
  BookOpen,
  Bot,
  Brain,
  Briefcase,
  Building2,
  Calendar,
  CalendarDays,
  Check,
  CheckCircle2,
  CircleAlert,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ClipboardList,
  Clock,
  Cloud,
  Coffee,
  Copy,
  Crown,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  FileText,
  Filter,
  Flag,
  Flame,
  Folder,
  FolderOpen,
  GanttChart,
  Globe,
  GripVertical,
  Handshake,
  HardHat,
  PenLine,
  Headphones,
  Heart,
  Home,
  Image,
  Inbox,
  Info,
  Keyboard,
  Layers,
  Lightbulb,
  Link,
  Loader2,
  Lock,
  LogOut,
  Mail,
  Maximize2,
  Menu,
  Minimize2,
  MessageCircle,
  MessageSquare,
  Mic,
  Minus,
  Moon,
  MoreHorizontal,
  MoreVertical,
  Paperclip,
  Pencil,
  Phone,
  Pin,
  Plus,
  Pointer,
  Recycle,
  RefreshCw,
  Repeat,
  Reply,
  Rocket,
  Save,
  Search,
  Send,
  Settings,
  Share2,
  Shield,
  ShieldCheck,
  SmilePlus,
  SlidersHorizontal,
  Smartphone,
  Snowflake,
  Sparkles,
  Star,
  Sun,
  Tag,
  Target,
  Ticket,
  Timer,
  Trash2,
  TreePalm,
  TrendingUp,
  Upload,
  User,
  UserPlus,
  Users,
  Video,
  Wrench,
  X,
  Zap,
} from 'lucide-react';

export const lucideMap = {
  activity: Activity,
  'alert-triangle': AlertTriangle,
  archive: Archive,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-down': ArrowDown,
  'arrow-up': ArrowUp,
  'arrow-up-right': ArrowUpRight,
  bell: Bell,
  'book-open': BookOpen,
  bot: Bot,
  brain: Brain,
  briefcase: Briefcase,
  building: Building2,
  calendar: Calendar,
  'calendar-days': CalendarDays,
  check: Check,
  'check-circle': CheckCircle2,
  'circle-alert': CircleAlert,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  'clipboard-list': ClipboardList,
  clock: Clock,
  cloud: Cloud,
  coffee: Coffee,
  copy: Copy,
  crown: Crown,
  download: Download,
  'external-link': ExternalLink,
  eye: Eye,
  'eye-off': EyeOff,
  'file-text': FileText,
  filter: Filter,
  flag: Flag,
  flame: Flame,
  folder: Folder,
  'folder-open': FolderOpen,
  'gantt-chart': GanttChart,
  globe: Globe,
  'grip-vertical': GripVertical,
  handshake: Handshake,
  'hard-hat': HardHat,
  headphones: Headphones,
  heart: Heart,
  home: Home,
  image: Image,
  inbox: Inbox,
  info: Info,
  keyboard: Keyboard,
  layers: Layers,
  lightbulb: Lightbulb,
  link: Link,
  'loader-2': Loader2,
  lock: Lock,
  logout: LogOut,
  mail: Mail,
  'maximize-2': Maximize2,
  menu: Menu,
  'minimize-2': Minimize2,
  'message-circle': MessageCircle,
  'message-square': MessageSquare,
  mic: Mic,
  minus: Minus,
  moon: Moon,
  'more-horizontal': MoreHorizontal,
  'more-vertical': MoreVertical,
  paperclip: Paperclip,
  pencil: Pencil,
  'pen-line': PenLine,
  phone: Phone,
  pin: Pin,
  plus: Plus,
  pointer: Pointer,
  recycle: Recycle,
  'refresh-cw': RefreshCw,
  repeat: Repeat,
  reply: Reply,
  rocket: Rocket,
  save: Save,
  search: Search,
  send: Send,
  settings: Settings,
  'share-2': Share2,
  shield: Shield,
  'shield-check': ShieldCheck,
  'smile-plus': SmilePlus,
  sliders: SlidersHorizontal,
  smartphone: Smartphone,
  snowflake: Snowflake,
  sparkles: Sparkles,
  star: Star,
  sun: Sun,
  tag: Tag,
  target: Target,
  ticket: Ticket,
  timer: Timer,
  trash: Trash2,
  'tree-palm': TreePalm,
  'trending-up': TrendingUp,
  upload: Upload,
  user: User,
  'user-plus': UserPlus,
  users: Users,
  video: Video,
  wrench: Wrench,
  x: X,
  zap: Zap,
};

/** Map emoji UI shortcuts to lucide icon names */
export const emojiToIcon = {
  '🔍': 'search',
  '⚙️': 'settings',
  '⚙': 'settings',
  '🚪': 'logout',
  '💬': 'message-circle',
  '🔔': 'bell',
  '🌍': 'globe',
  '📖': 'book-open',
  '🎫': 'ticket',
  '✏️': 'pencil',
  '✏': 'pencil',
  '🗑️': 'trash',
  '🗑': 'trash',
  '➕': 'plus',
  '✖': 'x',
  '✕': 'x',
  '⚠️': 'alert-triangle',
  '⚠': 'alert-triangle',
  '✅': 'check-circle',
  '✨': 'sparkles',
  '🤖': 'bot',
  '⚡': 'zap',
  '🚀': 'rocket',
  '💡': 'lightbulb',
  '📅': 'calendar',
  '🗓️': 'calendar-days',
  '🗓': 'calendar-days',
  '📋': 'clipboard-list',
  '👤': 'user',
  '🔒': 'lock',
  '👁️': 'eye',
  '👁': 'eye',
  '🙈': 'eye-off',
  '🏠': 'home',
  '💾': 'save',
  '🔗': 'link',
  '🎛️': 'sliders',
  '📝': 'file-text',
  '💼': 'briefcase',
  '📊': 'trending-up',
  '🔄': 'refresh-cw',
  '❌': 'x',
  '⭐': 'star',
  '📌': 'pin',
  '🔥': 'flame',
  '💻': 'bot',
  '📱': 'smartphone',
  '🌙': 'moon',
  '☀️': 'sun',
  '☀': 'sun',
  '👥': 'users',
  '📈': 'trending-up',
  '🛡️': 'shield',
  '🛡': 'shield',
  '🔑': 'lock',
  '📤': 'upload',
  '📥': 'download',
  '🗂️': 'layers',
  '🏷️': 'tag',
  '⏰': 'clock',
  '⏳': 'clock',
  '🖼️': 'image',
  '🔧': 'wrench',
  '📦': 'archive',
  '🌐': 'globe',
  '🤝': 'handshake',
  '📍': 'pin',
  '📁': 'folder',
  '📂': 'folder-open',
  '🧠': 'brain',
  '🏢': 'building',
  'ℹ️': 'info',
  'ℹ': 'info',
  '👋': 'handshake',
  '🧊': 'snowflake',
  '📎': 'paperclip',
  '🎨': 'image',
  '☁️': 'cloud',
  '☁': 'cloud',
  '🔐': 'shield-check',
  '🚨': 'circle-alert',
  '📄': 'file-text',
  '👉': 'pointer',
  '🎯': 'target',
  '🍅': 'timer',
  '☕': 'coffee',
  '🕒': 'clock',
  '🛤️': 'gantt-chart',
  '🛤': 'gantt-chart',
  '🔁': 'repeat',
  '🎧': 'headphones',
  '👑': 'crown',
  '📭': 'inbox',
  '🌴': 'tree-palm',
  '🎌': 'flag',
  '⌨️': 'keyboard',
  '⌨': 'keyboard',
  '🕵️': 'eye-off',
  '🕵': 'eye-off',
  '💥': 'zap',
  '❄️': 'snowflake',
  '❄': 'snowflake',
  '♻️': 'recycle',
  '♻': 'recycle',
  '↗': 'arrow-up-right',
  '⏱️': 'timer',
  '⏱': 'timer',
  '🏗️': 'hard-hat',
  '🏗': 'hard-hat',
  '✍️': 'pen-line',
  '✍': 'pen-line',
};
