"""add_custom_project_task

Revision ID: 01bc0511f253
Revises: f1f6cb435a0a
Create Date: 2026-07-16 15:24:22.551518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01bc0511f253'
down_revision: Union[str, Sequence[str], None] = 'f1f6cb435a0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timesheets', sa.Column('custom_project_name', sa.String(length=255), nullable=True))
    op.add_column('timesheets', sa.Column('custom_task_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timesheets', 'custom_task_name')
    op.drop_column('timesheets', 'custom_project_name')
    # ### end Alembic commands ###
