"""Add timesheets

Revision ID: f1f6cb435a0a
Revises: 5bad02e9bf55
Create Date: 2026-07-16 14:01:26.991446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1f6cb435a0a'
down_revision: Union[str, Sequence[str], None] = '5bad02e9bf55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('requests_timestamp_key'), 'requests', type_='unique')
    op.alter_column('subtasks', 'assignee',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.add_column('users', sa.Column('timesheet_approver', sa.String(length=50), nullable=True))
    op.alter_column('users', 'account_status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'active'::text"))
    op.drop_column('users', 'tier')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tier', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.alter_column('users', 'account_status',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'active'::text"))
    op.drop_column('users', 'timesheet_approver')
    op.alter_column('subtasks', 'assignee',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_unique_constraint(op.f('requests_timestamp_key'), 'requests', ['timestamp'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
